### ISSUE TITLE
Removal not working

### ISSUE THREAD

**Issue by xeruf** [ConnerWill/yayfzf#2]
Nifty tool!

Unfortunately when I invoke `C-r`, I always get an error like this:

```sh
❯ yayfzf
Removing ...
Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/  
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/  
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : community/syncthing (Installed)                                                       : Open Source Continuous Replication / Cluster Synchronization Thing
error: target not found: community/syncthing (Installed)                                                       : Open Source Continuous Replication / Cluster Synchronization
 Thing
 -> exit status 1
```

**Comment by ConnerWill** [comment]
@xeruf

I fixed the issue with removing packages. I also fixed installing packages. See [this commit](https://github.com/ConnerWill/yayfzf/commit/e4b5f1f052c8676638db90d59089035a3a9f7aac)

I will be updating ***yayfzf*** in the AUR soon. I will close this issue once it has been updated in the AUR.

**Comment by ConnerWill** [comment]
@xeruf 

Updated AUR package

Update your packages and try again. Let me know if this solves the problem

```bash
yay -Syu
```
